### ISSUE TITLE
Include feed experation date

### ISSUE THREAD

**Issue by ustroetz** [transitland/transitland-feed-registry#26]
GTFS feeds become invalid or non-usable if the `end_date` of the `calendar.txt` is older than the current date. See [here](https://developers.google.com/transit/gtfs/examples/gtfs-feed#calendartxt) for instance. 

Wouldn't it make sense to include that "expire date" in the feeds JSON in order to check easier if a feed is about to expire and get an alert?

Or maybe this is something that should be checked in the Transitland Datastore?

I am curious if you guys have put any thought in this yet?

**Comment by drewda** [comment]
Thanks for the suggestion, @ustroetz. This is functionality we're currently developing for the Transitland Datastore.

The point of this registry is to keep static information like feed URLs and license information. The Datastore includes a "feed eater" process, which can poll feeds and update records with information like calendars.
